#[
CAVE_ID			"T.F-10.01"
CAVE_NAME		"Jaskinia Lodowa w Ciemniaku"
UPDATE_DATE		2026-04-16
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Pawel Gogolak"
COORDINATOR_EMAIL	"pafffel@gmail.com"
REFERENCE_SYSTEM	"WGS84"
COORDINATE_SYSTEM	"UTM"
DATA_SOURCE		"Panstwowy Instytut Geologiczny"
LICENSE			"http://creativecommons.org/licenses/by-sa/4.0/"
#]

#prefix LodowaWCiemniaku
#flag	gc0	/Lodowa w Ciemniaku
#flag	gc0	/ENTRANCE
#note	gc0	/Lodowa w Ciemniaku
#fix	gc0	E19.892083	N49.233889	1695.2
