#[
CAVE_ID			"T.E-08.18"
CAVE_NAME		"Jaskinia Poszukiwaczy Skarbow"
UPDATE_DATE		2026-03-07
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
REFERENCE_SYSTEM	"WGS84"
COORDINATE_SYSTEM	"UTM"
DATA_SOURCE		"Panstwowy Instytut Geologiczny"
LICENSE			"http://creativecommons.org/licenses/by-sa/4.0/"
#]

#prefix poszuk
#flag	0	/Jaskinia Poszukiwaczy Skarbow
#note	0	/Jaskinia Poszukiwaczy Skarbow
#fix	0	E19.866011	N49.236997	1211.0m
