#[
CAVE_ID			"T.E-08.01"
CAVE_NAME		"Jaskinia Pod Zamkiem"
UPDATE_DATE		2026-03-07
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
REFERENCE_SYSTEM	"WGS84"
COORDINATE_SYSTEM	"UTM"
DATA_SOURCE		"Panstwowy Instytut Geologiczny"
LICENSE			"http://creativecommons.org/licenses/by-sa/4.0/"
#]

#prefix podzamk
#flag	0	/Jaskinia Pod Zamkiem
#flag	0	/ENTRANCE
#note	0	/Jaskinia Pod Zamkiem
#fix	0	E19.864730	N49.237658	1186.0m
