#date 2026-05-09
#units meters order=ENU

; Wspolrzedne #fix sa automatycznie wstrzykiwane z release'ow:
; https://github.com/dlubom/gps-kataster-obiektow-tatr/releases/tag/v1.0.0
; Szczegoly pomiarow i wyboru najlepszych wartosci sa w tamtym projekcie.

#fix	BandziochKom:000	E19.8495785	N49.24258746	1451.06m (R0.01,R0.01)
#flag	BandziochKom:000	/Bandzioch Kom. Dolny
#flag	BandziochKom:000	/ENTRANCE
#note	BandziochKom:000	/Bandzioch Kom. Dolny

#fix	BandziochKom:136	E19.8437239672	N49.2425632426	1675.02m (R0.01,R0.01)
#flag	BandziochKom:136	/Bandzioch Kom. Gorny
#flag	BandziochKom:136	/ENTRANCE
#note	BandziochKom:136	/Bandzioch Kom. Gorny

#fix	Biala:0	E19.8696888666	N49.247219476	1283m
#flag	Biala:0	/Jaskinia Biala
#flag	Biala:0	/ENTRANCE
#note	Biala:0	/Jaskinia Biala

#fix	Ciepla:0	E19.8655805119	N49.2334694065	1335.861923m
#flag	Ciepla:0	/Jaskinia Ciepla
#flag	Ciepla:0	/ENTRANCE
#note	Ciepla:0	/Jaskinia Ciepla

#fix	Czarna:Kujat:0	E19.8812979507	N49.2470745479	1403.92m
#flag	Czarna:Kujat:0	/Jaskinia Czarna III
#flag	Czarna:Kujat:0	/ENTRANCE
#note	Czarna:Kujat:0	/Jaskinia Czarna III

#fix	Czarna:M:otwor1	E19.8705053667	N49.2444121431	1323.42m
#flag	Czarna:M:otwor1	/Jaskinia Czarna
#flag	Czarna:M:otwor1	/ENTRANCE
#note	Czarna:M:otwor1	/Jaskinia Czarna

#fix	CzerwonaStudzienka:0	E19.9138972724	N49.244777783	1811.963374m
#flag	CzerwonaStudzienka:0	/Czerwona Studzienka
#flag	CzerwonaStudzienka:0	/ENTRANCE
#note	CzerwonaStudzienka:0	/Czerwona Studzienka

#fix	Dmuchawa:0	E19.8209999681	N49.2461111561	1301.465712m
#flag	Dmuchawa:0	/Dmuchawa
#flag	Dmuchawa:0	/ENTRANCE
#note	Dmuchawa:0	/Dmuchawa

#fix	Dziura:0	E19.9428888046	N49.2720610402	1008.043065m
#flag	Dziura:0	/Jaskinia Dziura
#flag	Dziura:0	/ENTRANCE
#note	Dziura:0	/Jaskinia Dziura

#fix	DziuraPodSwist:dps0	E19.9241116012	N49.2409679777	1685.524588m
#flag	DziuraPodSwist:dps0	/Pod Swistowa
#flag	DziuraPodSwist:dps0	/ENTRANCE
#note	DziuraPodSwist:dps0	/Pod Swistowa

#fix	DziuraWStole:0	E19.9050888491	N49.2239972427	1894.051995m
#flag	DziuraWStole:0	/Dziura w Stole
#flag	DziuraWStole:0	/ENTRANCE
#note	DziuraWStole:0	/Dziura w Stole

#fix	DziurkaWTrawce:0	E19.9090725865	N49.2426103267	1760.114035m
#flag	DziurkaWTrawce:0	/Dziurka w Trawce
#flag	DziurkaWTrawce:0	/ENTRANCE
#note	DziurkaWTrawce:0	/Dziurka w Trawce

#fix	Gawra:0	E19.8749033227	N49.2371459809	1298.055213m
#flag	Gawra:0	/Gawra
#flag	Gawra:0	/ENTRANCE
#note	Gawra:0	/Gawra

#fix	Goryczkowa:M:0	E19.9722720103	N49.2524095105	1234.324535m
#flag	Goryczkowa:M:0	/Jaskinia Goryczkowa
#flag	Goryczkowa:M:0	/ENTRANCE
#note	Goryczkowa:M:0	/Jaskinia Goryczkowa

#fix	Harda:1.0	E19.9079722582	N49.2427499929	1668.907354m
#flag	Harda:1.0	/Harda
#flag	Harda:1.0	/ENTRANCE
#note	Harda:1.0	/Harda

#fix	Kalacka:0	E19.9677461163	N49.2563866143	1225.250995m
#flag	Kalacka:0	/Jaskinia Kalacka
#flag	Kalacka:0	/ENTRANCE
#note	Kalacka:0	/Jaskinia Kalacka

#fix	KamienneMleko:0	E19.8108454857	N49.2454016643	1103.902233m
#flag	KamienneMleko:0	/Kamienne Mleko
#flag	KamienneMleko:0	/ENTRANCE
#note	KamienneMleko:0	/Kamienne Mleko

#fix	KasprowaNiznia:0	E19.9784804959	N49.2541341286	1216.555032m
#flag	KasprowaNiznia:0	/Kasprowa Niznia
#flag	KasprowaNiznia:0	/ENTRANCE
#note	KasprowaNiznia:0	/Kasprowa Niznia

#fix	KoprowaStudnia:ks0	E19.9302480672	N49.2393472935	1808.930858m
#flag	KoprowaStudnia:ks0	/Koprowa Studnia
#flag	KoprowaStudnia:ks0	/ENTRANCE
#note	KoprowaStudnia:ks0	/Koprowa Studnia

#fix	Koszowa:0	E20.0596944311	N49.2491388961	1763.604m
#flag	Koszowa:0	/Jaskinia Koszowa
#flag	Koszowa:0	/ENTRANCE
#note	Koszowa:0	/Jaskinia Koszowa

#fix	Kozia:k001	E19.9080642201	N49.2388387835	1835.745891m
#flag	Kozia:k001	/Kozia
#flag	Kozia:k001	/ENTRANCE
#note	Kozia:k001	/Kozia

#fix	Lejbusiowa:A1	E19.9004138726	N49.2385606103	1838.365497m
#flag	Lejbusiowa:A1	/Jaskinia Lejbusiowa
#flag	Lejbusiowa:A1	/ENTRANCE
#note	Lejbusiowa:A1	/Jaskinia Lejbusiowa

#fix	LodowaMalolacka:0	E19.9285195	N49.2431332993	1637.100508m
#flag	LodowaMalolacka:0	/Lodowa Malolacka
#flag	LodowaMalolacka:0	/ENTRANCE
#note	LodowaMalolacka:0	/Lodowa Malolacka

#fix	LodowaMietusia:0	E19.9017112761	N49.2399201817	1586.427564m
#flag	LodowaMietusia:0	/Jaskinia Lodowa Mietusia
#flag	LodowaMietusia:0	/ENTRANCE
#note	LodowaMietusia:0	/Jaskinia Lodowa Mietusia

#fix	LodowaWCiemniaku:gc0	E19.8924846728	N49.2339748019	1710.855862m
#flag	LodowaWCiemniaku:gc0	/Lodowa w Ciemniaku
#flag	LodowaWCiemniaku:gc0	/ENTRANCE
#note	LodowaWCiemniaku:gc0	/Lodowa w Ciemniaku

#fix	LustrzanyKorytarz:0	E19.878349949	N49.2375305884	1487.553331m
#flag	LustrzanyKorytarz:0	/Lustrzany Korytarz
#flag	LustrzanyKorytarz:0	/ENTRANCE
#note	LustrzanyKorytarz:0	/Lustrzany Korytarz

#fix	MalaWMulowej:1	E19.9022258853	N49.2382581726	1753.068244m
#flag	MalaWMulowej:1	/Jaskinia Mala w Mulowej
#flag	MalaWMulowej:1	/ENTRANCE
#note	MalaWMulowej:1	/Jaskinia Mala w Mulowej

#fix	Malolacka:ma0	E19.921435723	N49.2390975003	1871.759178m
#flag	Malolacka:ma0	/Malolacka
#flag	Malolacka:ma0	/ENTRANCE
#note	Malolacka:ma0	/Malolacka

#fix	Marmurowa:0	E19.9008006292	N49.2393721035	1767.702373m
#flag	Marmurowa:0	/Marmurowa
#flag	Marmurowa:0	/ENTRANCE
#note	Marmurowa:0	/Marmurowa

#fix	MeanderWMalymSiodle:0	E19.9126816925	N49.2453624619	1793.610911m
#flag	MeanderWMalymSiodle:0	/Meander w Malolackim Siodle
#flag	MeanderWMalymSiodle:0	/ENTRANCE
#note	MeanderWMalymSiodle:0	/Meander w Malolackim Siodle

#fix	Mietusia:ru_0	E19.8987424675	N49.2464077315	1271.290985m
#flag	Mietusia:ru_0	/Jaskinia Mietusia
#flag	Mietusia:ru_0	/ENTRANCE
#note	Mietusia:ru_0	/Jaskinia Mietusia

#fix	MietusiaWyznia:ot_0	E19.8948992419	N49.2454610045	1383.993046m
#flag	MietusiaWyznia:ot_0	/Jaskinia Mietusia Wyznia
#flag	MietusiaWyznia:ot_0	/ENTRANCE
#note	MietusiaWyznia:ot_0	/Jaskinia Mietusia Wyznia

#fix	MnichStudniaWyz:0	E19.9296360655	N49.243238865	1699.893361m
#flag	MnichStudniaWyz:0	/Mnichowa Studnia Wyznia
#flag	MnichStudniaWyz:0	/ENTRANCE
#note	MnichStudniaWyz:0	/Mnichowa Studnia Wyznia

#fix	Mrozna:0	E19.8672300982	N49.2498018833	1111.121897m
#flag	Mrozna:0	/Jaskinia Mrozna
#flag	Mrozna:0	/ENTRANCE
#note	Mrozna:0	/Jaskinia Mrozna

#fix	NadBeczka:0	E19.8837305401	N49.2338805908	1413.757328m
#flag	NadBeczka:0	/Jaskinia nad Beczka
#flag	NadBeczka:0	/ENTRANCE
#note	NadBeczka:0	/Jaskinia nad Beczka

#fix	NadPercia:0	E19.874011053	N49.2366305758	1255.404836m
#flag	NadPercia:0	/Jaskinia nad Percia
#flag	NadPercia:0	/ENTRANCE
#note	NadPercia:0	/Jaskinia nad Percia

#fix	NovaKresanica:nvk0	E19.91418777	N49.22918839	2016m
#flag	NovaKresanica:nvk0	/Nova Kresanica
#flag	NovaKresanica:nvk0	/ENTRANCE
#note	NovaKresanica:nvk0	/Nova Kresanica

#fix	ObcasnaVyv:A1:o1	E19.92986944	N49.22661111	1453m
#flag	ObcasnaVyv:A1:o1	/Obcasna Vyvieracka
#flag	ObcasnaVyv:A1:o1	/ENTRANCE
#note	ObcasnaVyv:A1:o1	/Obcasna Vyvieracka

#fix	Pawlikowskiego:Mylna:0	E19.8622047217	N49.2393861277	1098m
#flag	Pawlikowskiego:Mylna:0	/Mylna
#flag	Pawlikowskiego:Mylna:0	/ENTRANCE
#note	Pawlikowskiego:Mylna:0	/Mylna

#fix	Pawlikowskiego:Oblazkowa:0.0	E19.8625797302	N49.239561635	1096.62m
#flag	Pawlikowskiego:Oblazkowa:0.0	/Oblazkowa
#flag	Pawlikowskiego:Oblazkowa:0.0	/ENTRANCE
#note	Pawlikowskiego:Oblazkowa:0.0	/Oblazkowa

#fix	Pawlikowskiego:Raptawicka:1.0	E19.8622197642	N49.2398675351	1141.31m
#flag	Pawlikowskiego:Raptawicka:1.0	/Raptawicka
#flag	Pawlikowskiego:Raptawicka:1.0	/ENTRANCE
#note	Pawlikowskiego:Raptawicka:1.0	/Raptawicka

#fix	PodProgiem:0	E19.9158398884	N49.2451308705	1760.029097m
#flag	PodProgiem:0	/Jaskinia pod Progiem
#flag	PodProgiem:0	/ENTRANCE
#note	PodProgiem:0	/Jaskinia pod Progiem

#fix	PodZamkiem:0	E19.8647299874	N49.2376579126	1194.025597m
#flag	PodZamkiem:0	/Jaskinia Pod Zamkiem
#flag	PodZamkiem:0	/ENTRANCE
#note	PodZamkiem:0	/Jaskinia Pod Zamkiem

#fix	PoszukiwaczySkarbow:0	E19.8656429623	N49.2367678215	1201.8467m
#flag	PoszukiwaczySkarbow:0	/Jaskinia Poszukiwaczy Skarbow
#flag	PoszukiwaczySkarbow:0	/ENTRANCE
#note	PoszukiwaczySkarbow:0	/Jaskinia Poszukiwaczy Skarbow

#fix	PrzyJedrusiowej:pj0	E19.9239694605	N49.2419527881	1560.056048m
#flag	PrzyJedrusiowej:pj0	/Przy Jedrusiowej Dziurze
#flag	PrzyJedrusiowej:pj0	/ENTRANCE
#note	PrzyJedrusiowej:pj0	/Przy Jedrusiowej Dziurze

#fix	PrzyPrzechodzie:jp0	E19.9239639069	N49.2417361581	1589.153993m
#flag	PrzyPrzechodzie:jp0	/Przy Przechodzie
#flag	PrzyPrzechodzie:jp0	/ENTRANCE
#note	PrzyPrzechodzie:jp0	/Przy Przechodzie

#fix	PtasiaStudnia:a14	E19.9055153249	N49.2407775482	1574.186504m
#flag	PtasiaStudnia:a14	/Lodowa Litworowa
#flag	PtasiaStudnia:a14	/ENTRANCE
#note	PtasiaStudnia:a14	/Lodowa Litworowa

#fix	PtasiaStudnia:a22	E19.9050742888	N49.2408583882	1525.858298m
#flag	PtasiaStudnia:a22	/Jaskinia nad Dachem
#flag	PtasiaStudnia:a22	/ENTRANCE
#note	PtasiaStudnia:a22	/Jaskinia nad Dachem

#fix	PtasiaStudnia:A7	E19.9056895545	N49.2407384803	1590.768246m
#flag	PtasiaStudnia:A7	/Jaskinia nad Lodowa Litworowa
#flag	PtasiaStudnia:A7	/ENTRANCE
#note	PtasiaStudnia:A7	/Jaskinia nad Lodowa Litworowa

#fix	PtasiaStudnia:b1	E19.904786239	N49.2400759201	1650.610092m
#flag	PtasiaStudnia:b1	/Ptasia Studnia
#flag	PtasiaStudnia:b1	/ENTRANCE
#note	PtasiaStudnia:b1	/Ptasia Studnia

#fix	RuraPrzyOknie:0	E19.8710384124	N49.2363680593	1187.845053m
#flag	RuraPrzyOknie:0	/Rura przy Oknie
#flag	RuraPrzyOknie:0	/ENTRANCE
#note	RuraPrzyOknie:0	/Rura przy Oknie

#fix	SchronPodJedrus:spj0	E19.9238305721	N49.2419777439	1566.360608m
#flag	SchronPodJedrus:spj0	/Schron pod Jedrusiowa Dziura
#flag	SchronPodJedrus:spj0	/ENTRANCE
#note	SchronPodJedrus:spj0	/Schron pod Jedrusiowa Dziura

#fix	SmoczaJama:0	E19.8676026051	N49.2378091364	1094.750535m
#flag	SmoczaJama:0	/Smocza Jama
#flag	SmoczaJama:0	/ENTRANCE
#note	SmoczaJama:0	/Smocza Jama

#fix	SnieznaStudnia:ss0	E19.9227323194	N49.2414882965	1755.166511m
#flag	SnieznaStudnia:ss0	/Sniezna Studnia
#flag	SnieznaStudnia:ss0	/ENTRANCE
#note	SnieznaStudnia:ss0	/Sniezna Studnia

#fix	SpiacychRycerzy:1	E19.9234167358	N49.2499055921	1409.875774m
#flag	SpiacychRycerzy:1	/Jaskinia Spiacych Rycerzy
#flag	SpiacychRycerzy:1	/ENTRANCE
#note	SpiacychRycerzy:1	/Jaskinia Spiacych Rycerzy

#fix	StudniaNaSzlaku:0	E19.9132160713	N49.2443274163	1799.710772m
#flag	StudniaNaSzlaku:0	/Studnia na Szlaku
#flag	StudniaNaSzlaku:0	/ENTRANCE
#note	StudniaNaSzlaku:0	/Studnia na Szlaku

#fix	StudniaPrzyPrzech:spp0	E19.9235972706	N49.2418333002	1609.312672m
#flag	StudniaPrzyPrzech:spp0	/Studnia przy Przechodzie
#flag	StudniaPrzyPrzech:spp0	/ENTRANCE
#note	StudniaPrzyPrzech:spp0	/Studnia przy Przechodzie

#fix	StudniaWKazalnicy:SwK0	E19.9015890141	N49.2400736538	1521.278282m
#flag	StudniaWKazalnicy:SwK0	/Studnia w Kazalnicy
#flag	StudniaWKazalnicy:SwK0	/ENTRANCE
#note	StudniaWKazalnicy:SwK0	/Studnia w Kazalnicy

#fix	Swistacza:24	E19.930667961	N49.2393143075	1814.340872m
#flag	Swistacza:24	/Jaskinia Swistacza
#flag	Swistacza:24	/ENTRANCE
#note	Swistacza:24	/Jaskinia Swistacza

#fix	SzaraStudnia:0	E19.9123722601	N49.2441361256	1751.160829m
#flag	SzaraStudnia:0	/Szara Studnia
#flag	SzaraStudnia:0	/ENTRANCE
#note	SzaraStudnia:0	/Szara Studnia

#fix	SzczelinaMietusia:0	E19.9025138845	N49.2398777414	1547.98098m
#flag	SzczelinaMietusia:0	/Szczelina Mietusia
#flag	SzczelinaMietusia:0	/ENTRANCE
#note	SzczelinaMietusia:0	/Szczelina Mietusia

#fix	SzczelinaNadLejem:0	E20.0575556045	N49.2491666848	1762.278017m
#flag	SzczelinaNadLejem:0	/Szczelina nad Lejem
#flag	SzczelinaNadLejem:0	/ENTRANCE
#note	SzczelinaNadLejem:0	/Szczelina nad Lejem

#fix	SzczelinaNadTomI:0	E19.9034111262	N49.2296388839	2022.552263m
#flag	SzczelinaNadTomI:0	/Szczelina nad Tomanowa I
#flag	SzczelinaNadTomI:0	/ENTRANCE
#note	SzczelinaNadTomI:0	/Szczelina nad Tomanowa I

#fix	SzczelinaNadTomII:0	E19.903269437	N49.229750039	2027.837951m
#flag	SzczelinaNadTomII:0	/Szczelina nad Tomanowa II
#flag	SzczelinaNadTomII:0	/ENTRANCE
#note	SzczelinaNadTomII:0	/Szczelina nad Tomanowa II

#fix	Uplazkowa:ju0	E19.9222163652	N49.2419654473	1688.357814m
#flag	Uplazkowa:ju0	/Uplazkowa
#flag	Uplazkowa:ju0	/ENTRANCE
#note	Uplazkowa:ju0	/Uplazkowa

#fix	WielkaSniezna:Ciag:0	E19.920874362	N49.2395339761	1873.705619m
#flag	WielkaSniezna:Ciag:0	/Nad Kotliny
#flag	WielkaSniezna:Ciag:0	/ENTRANCE
#note	WielkaSniezna:Ciag:0	/Nad Kotliny

#fix	WielkaSniezna:Ciag:s68	E19.926428687	N49.2401852986	1699.800044m
#flag	WielkaSniezna:Ciag:s68	/Sniezna
#flag	WielkaSniezna:Ciag:s68	/ENTRANCE
#note	WielkaSniezna:Ciag:s68	/Sniezna

#fix	WielkaSniezna:Jasna:j0	E19.921336079	N49.2396138869	1849.461862m
#flag	WielkaSniezna:Jasna:j0	/Jasny Awen
#flag	WielkaSniezna:Jasna:j0	/ENTRANCE
#note	WielkaSniezna:Jasna:j0	/Jasny Awen

#fix	WielkaSniezna:Litworowa:LT58	E19.9147636451	N49.238511573	1905.290951m
#flag	WielkaSniezna:Litworowa:LT58	/Wielka Litworowa
#flag	WielkaSniezna:Litworowa:LT58	/ENTRANCE
#note	WielkaSniezna:Litworowa:LT58	/Wielka Litworowa

#fix	WielkiejTurni:0	E19.9204261369	N49.2449416319	1821.308475m
#flag	WielkiejTurni:0	/Jaskinia w Wielkiej Turni
#flag	WielkiejTurni:0	/ENTRANCE
#note	WielkiejTurni:0	/Jaskinia w Wielkiej Turni

#fix	WilczySchron:wsn0	E19.9243767411	N49.2413457566	1635.256335m
#flag	WilczySchron:wsn0	/Wilczy Schron
#flag	WilczySchron:wsn0	/ENTRANCE
#note	WilczySchron:wsn0	/Wilczy Schron

; Wysoka7Progow: aktywny #fix opieramy tylko na source: unknown - GNSS dla W7-0.
; To najdokladniejszy pomiar; pozostale powiazania GPS sa niepewne, wiec
; renderujemy je nizej tylko jako zakomentowane wartosci kontrolne.
; Brak gps_fix: w gps-kataster-obiektow-tatr nie ma osobnego object_id dla tego lokalnego otworu.
#flag	Wysoka7Progow:W-300	/ENTRANCE
#note	Wysoka7Progow:W-300	/Wysoka Gorny Otwor

; source: unknown - GNSS
#fix	Wysoka7Progow:W7-0	E19.88454604	N49.2336413	1486.69m
#flag	Wysoka7Progow:W7-0	/Otwor
#flag	Wysoka7Progow:W7-0	/Wysoka-Za7 Progami
#flag	Wysoka7Progow:W7-0	/ENTRANCE
#note	Wysoka7Progow:W7-0	/Wysoka-Za7 Progami

; #fix	Wysoka7Progow:W7-200	E19.8844821579	N49.233618932	1471.854856m
#flag	Wysoka7Progow:W7-200	/ENTRANCE
#note	Wysoka7Progow:W7-200	/Za7Progami Dolny Otwor

; #fix	Wysoka7Progow:W7-500	E19.884345891	N49.2337135556	1460.720658m
#flag	Wysoka7Progow:W7-500	/ENTRANCE
#note	Wysoka7Progow:W7-500	/Za7Progami Gorny Otwor

#fix	WyzKoszowaDziura:0	E20.0586945001	N49.248722182	1794.824636m
#flag	WyzKoszowaDziura:0	/Wyznia Koszowa Dziura
#flag	WyzKoszowaDziura:0	/ENTRANCE
#note	WyzKoszowaDziura:0	/Wyznia Koszowa Dziura

#fix	ZaspalkowaSzczel:zss0	E19.9277110763	N49.2386194128	1742.045049m
#flag	ZaspalkowaSzczel:zss0	/Zaspalkowa
#flag	ZaspalkowaSzczel:zss0	/ENTRANCE
#note	ZaspalkowaSzczel:zss0	/Zaspalkowa

#fix	ZawaliskawaTom:0	E19.8955805968	N49.2293305786	1758.972022m
#flag	ZawaliskawaTom:0	/Jaskinia Zawaliskowa Tomanowa
#flag	ZawaliskawaTom:0	/ENTRANCE
#note	ZawaliskawaTom:0	/Jaskinia Zawaliskowa Tomanowa

#fix	ZawalonySchron:0	E19.9133713083	N49.2455308547	1753.281916m
#flag	ZawalonySchron:0	/Zawalony Schron
#flag	ZawalonySchron:0	/ENTRANCE
#note	ZawalonySchron:0	/Zawalony Schron

#fix	ZbojeckaDziura:0	E19.8116825345	N49.2476094896	1141.561625m
#flag	ZbojeckaDziura:0	/Zbojecka Dziura
#flag	ZbojeckaDziura:0	/ENTRANCE
#note	ZbojeckaDziura:0	/Zbojecka Dziura

#fix	ZbojnickaPiwnica:0	E19.8652806158	N49.2364305882	1277.036537m
#flag	ZbojnickaPiwnica:0	/Zbojnicka Piwnica
#flag	ZbojnickaPiwnica:0	/ENTRANCE
#note	ZbojnickaPiwnica:0	/Zbojnicka Piwnica

#fix	ZbojnickaTurnia:0	E19.8652806158	N49.2364305882	1277.036537m
#flag	ZbojnickaTurnia:0	/Jaskinia w Zbojnickiej Turni
#flag	ZbojnickaTurnia:0	/ENTRANCE
#note	ZbojnickaTurnia:0	/Jaskinia w Zbojnickiej Turni

#fix	Ziobrowa:0	E19.8637944954	N49.2389055688	1075.590663m
#flag	Ziobrowa:0	/Jaskinia Ziobrowa
#flag	Ziobrowa:0	/ENTRANCE
#note	Ziobrowa:0	/Jaskinia Ziobrowa

; Ziobrowa:5.24 to drugi otwor SYSTEMU Ziobrowa.
; KSW-0177 jest pasujacym obiektem GPS, ale uzycie go jako aktywnego #fix
; rozciaga lokalny ciag poza geometrie pomiaru Ziobrowej.
; Zostawiamy wyrenderowana wspolrzedna zrodlowa do kontroli, ale jako komentarz,
; zeby Walls/Survex policzyl ten otwor z sieci pomiarowej.
; #fix	Ziobrowa:5.24	E19.864110606	N49.2383172488	1136.279224m
#flag	Ziobrowa:5.24	/Jaskinia pod Niznia Zbojnicka Turnia
#flag	Ziobrowa:5.24	/ENTRANCE
#note	Ziobrowa:5.24	/Jaskinia pod Niznia Zbojnicka Turnia

#fix	Zoska:0	E19.9148867846	N49.2448946642	1779.503338m
#flag	Zoska:0	/Jaskinia Zoska
#flag	Zoska:0	/ENTRANCE
#note	Zoska:0	/Jaskinia Zoska

#fix	Zoska:1Z	E19.9150109473	N49.2449125769	1777.284785m
#flag	Zoska:1Z	/Zagonna Studnia
#flag	Zoska:1Z	/ENTRANCE
#note	Zoska:1Z	/Zagonna Studnia

#fix	Zwolinskiego:0	E19.9773878837	N49.2513817668	1290.089909m
#flag	Zwolinskiego:0	/Zwolinskiego
#flag	Zwolinskiego:0	/ENTRANCE
#note	Zwolinskiego:0	/Zwolinskiego
