#date 2026-05-09
#units meters order=ENU

; Zbiorczy plik fixow otworow.
; Wspolrzedne #fix: WGS84 lon/lat w notacji decimal oraz wysokosc m n.p.m.
; Punkty przeliczane narzedziem cs2cs; uklad zrodlowy opisany przy grupie punktow, jesli znany.
; Wariancja R0.01 zostaje tylko przy Bandziochu: rozcina w Walls petle constrained #fix + RECT w BK-CG.SRV.

; source: unknown - GNSS
#fix	BandziochKom:000	E19.84957850	N49.24258746	1451.06m (R0.01,R0.01)
#flag	BandziochKom:000	/Bandzioch Kom. Dolny
#flag	BandziochKom:000	/ENTRANCE
#note	BandziochKom:000	/Bandzioch Kom. Dolny

#fix	BandziochKom:136	E19.8437239672	N49.2425632426	1675.02m (R0.01,R0.01)
#flag	BandziochKom:136	/Bandzioch Kom. Gorny
#flag	BandziochKom:136	/ENTRANCE
#note	BandziochKom:136	/Bandzioch Kom. Gorny

#fix	Biala:0	E19.8696888666	N49.2472194760	1283.00m
#flag	Biala:0	/Jaskinia Biala
#flag	Biala:0	/ENTRANCE
#note	Biala:0	/Jaskinia Biala

#fix	Ciepla:0	E19.8655800002	N49.2334699688	1331.00m
#flag	Ciepla:0	/Jaskinia Ciepla
#flag	Ciepla:0	/ENTRANCE
#note	Ciepla:0	/Jaskinia Ciepla

; source: GNSS + LIDAR 2026-05-09
; XY/H: PL-1992 EPSG:2180 (zrzut: easting,northing,H) + PL-KRON86-NH.
; Przeliczenie: cs2cs +init=epsg:2180 +to +init=epsg:4326, wejscie easting/northing.
; Czarna:M:otwor1: 563339.46 / 153353.95 / 1323.42 -> E19.8705053667 N49.2444121431 1323.42m
; Czarna:Kujat:0: 564121.29 / 153658.93 / 1403.92 -> E19.8812979507 N49.2470745479 1403.92m
#fix	Czarna:Kujat:0	E19.8812979507	N49.2470745479	1403.92m
#flag	Czarna:Kujat:0	/Jaskinia Czarna III
#flag	Czarna:Kujat:0	/ENTRANCE
#note	Czarna:Kujat:0	/Jaskinia Czarna III

#fix	Czarna:M:otwor1	E19.8705053667	N49.2444121431	1323.42m
#flag	Czarna:M:otwor1	/Jaskinia Czarna
#flag	Czarna:M:otwor1	/ENTRANCE
#note	Czarna:M:otwor1	/Jaskinia Czarna

#fix	CzerwonaStudzienka:0	E19.9138972136	N49.2447778127	1810.78m
#flag	CzerwonaStudzienka:0	/Czerwona Studzienka
#flag	CzerwonaStudzienka:0	/ENTRANCE
#note	CzerwonaStudzienka:0	/Czerwona Studzienka

#fix	Dmuchawa:0	E19.8210000469	N49.2461110261	1300.00m
#flag	Dmuchawa:0	/Dmuchawa
#flag	Dmuchawa:0	/ENTRANCE
#note	Dmuchawa:0	/Dmuchawa

#fix	Dziura:0	E19.9426667241	N49.2719055511	1020.00m
#flag	Dziura:0	/Jaskinia Dziura
#flag	Dziura:0	/ENTRANCE
#note	Dziura:0	/Jaskinia Dziura

#fix	DziuraPodSwist:dps0	E19.9242499774	N49.2411666659	1664.95m
#flag	DziuraPodSwist:dps0	/Pod Swistowa
#flag	DziuraPodSwist:dps0	/ENTRANCE
#note	DziuraPodSwist:dps0	/Pod Swistowa

#fix	DziuraWStole:0	E19.9050890660	N49.2239970286	1905.00m
#flag	DziuraWStole:0	/Dziura w Stole
#flag	DziuraWStole:0	/ENTRANCE
#note	DziuraWStole:0	/Dziura w Stole

#fix	DziurkaWTrawce:0	E19.9096277327	N49.2424999671	1762.55m
#flag	DziurkaWTrawce:0	/Dziurka w Trawce
#flag	DziurkaWTrawce:0	/ENTRANCE
#note	DziurkaWTrawce:0	/Dziurka w Trawce

#fix	Gawra:0	E19.8749029427	N49.2371460422	1303.00m
#flag	Gawra:0	/Gawra
#flag	Gawra:0	/ENTRANCE
#note	Gawra:0	/Gawra

#fix	Goryczkowa:M:0	E19.9726609951	N49.2511130237	1263.00m
#flag	Goryczkowa:M:0	/Jaskinia Goryczkowa
#flag	Goryczkowa:M:0	/ENTRANCE
#note	Goryczkowa:M:0	/Jaskinia Goryczkowa

#fix	Harda:1.0	E19.9079666541	N49.2427500021	1665.00m
#flag	Harda:1.0	/Harda
#flag	Harda:1.0	/ENTRANCE
#note	Harda:1.0	/Harda

#fix	Kalacka:0	E19.9668471971	N49.2562972367	1230.00m
#flag	Kalacka:0	/Jaskinia Kalacka
#flag	Kalacka:0	/ENTRANCE
#note	Kalacka:0	/Jaskinia Kalacka

#fix	KamienneMleko:0	E19.8110500518	N49.2453000154	1096.00m
#flag	KamienneMleko:0	/Kamienne Mleko
#flag	KamienneMleko:0	/ENTRANCE
#note	KamienneMleko:0	/Kamienne Mleko

#fix	KasprowaNiznia:0	E19.9785669763	N49.2539750281	1228.00m
#flag	KasprowaNiznia:0	/Kasprowa Niznia
#flag	KasprowaNiznia:0	/ENTRANCE
#note	KasprowaNiznia:0	/Kasprowa Niznia

#fix	KoprowaStudnia:ks0	E19.9303048216	N49.2393201728	1807.10m
#flag	KoprowaStudnia:ks0	/Koprowa Studnia
#flag	KoprowaStudnia:ks0	/ENTRANCE
#note	KoprowaStudnia:ks0	/Koprowa Studnia

#fix	Koszowa:0	E20.0596939415	N49.2491389625	1790.00m
#flag	Koszowa:0	/Jaskinia Koszowa
#flag	Koszowa:0	/ENTRANCE
#note	Koszowa:0	/Jaskinia Koszowa

#fix	Kozia:k001	E19.9082333219	N49.2389055165	1850.00m
#flag	Kozia:k001	/Kozia
#flag	Kozia:k001	/ENTRANCE
#note	Kozia:k001	/Kozia

#fix	Lejbusiowa:A1	E19.9009611748	N49.2387138558	1810.10m
#flag	Lejbusiowa:A1	/Jaskinia Lejbusiowa
#flag	Lejbusiowa:A1	/ENTRANCE
#note	Lejbusiowa:A1	/Jaskinia Lejbusiowa

#fix	LodowaMalolacka:0	E19.9284778438	N49.2430694628	1634.13m
#flag	LodowaMalolacka:0	/Lodowa Malolacka
#flag	LodowaMalolacka:0	/ENTRANCE
#note	LodowaMalolacka:0	/Lodowa Malolacka

#fix	LodowaMietusia:0	E19.9016360832	N49.2399361049	1589.70m
#flag	LodowaMietusia:0	/Jaskinia Lodowa Mietusia
#flag	LodowaMietusia:0	/ENTRANCE
#note	LodowaMietusia:0	/Jaskinia Lodowa Mietusia

#fix	LodowaWCiemniaku:gc0	E19.8920830294	N49.2338889581	1695.20m
#flag	LodowaWCiemniaku:gc0	/Lodowa w Ciemniaku
#flag	LodowaWCiemniaku:gc0	/ENTRANCE
#note	LodowaWCiemniaku:gc0	/Lodowa w Ciemniaku

#fix	LustrzanyKorytarz:0	E19.8783499550	N49.2375300302	1530.00m
#flag	LustrzanyKorytarz:0	/Lustrzany Korytarz
#flag	LustrzanyKorytarz:0	/ENTRANCE
#note	LustrzanyKorytarz:0	/Lustrzany Korytarz

#fix	MalaWMulowej:1	E19.9022082720	N49.2382944711	1753.67m
#flag	MalaWMulowej:1	/Jaskinia Mala w Mulowej
#flag	MalaWMulowej:1	/ENTRANCE
#note	MalaWMulowej:1	/Jaskinia Mala w Mulowej

#fix	Malolacka:ma0	E19.9217638572	N49.2386722499	1872.69m
#flag	Malolacka:ma0	/Malolacka
#flag	Malolacka:ma0	/ENTRANCE
#note	Malolacka:ma0	/Malolacka

#fix	Marmurowa:0	E19.9008138324	N49.2393917028	1770.60m
#flag	Marmurowa:0	/Marmurowa
#flag	Marmurowa:0	/ENTRANCE
#note	Marmurowa:0	/Marmurowa

#fix	MeanderWMalymSiodle:0	E19.9126833524	N49.2453888799	1794.70m
#flag	MeanderWMalymSiodle:0	/Meander w Malolackim Siodle
#flag	MeanderWMalymSiodle:0	/ENTRANCE
#note	MeanderWMalymSiodle:0	/Meander w Malolackim Siodle

#fix	Mietusia:ru_0	E19.8987270378	N49.2464814936	1275.03m
#flag	Mietusia:ru_0	/Jaskinia Mietusia
#flag	Mietusia:ru_0	/ENTRANCE
#note	Mietusia:ru_0	/Jaskinia Mietusia

#fix	MietusiaWyznia:ot_gps	E19.8948999471	N49.2453990405	1377.00m
#flag	MietusiaWyznia:ot_gps	/Jaskinia Mietusia Wyznia
#flag	MietusiaWyznia:ot_gps	/ENTRANCE
#note	MietusiaWyznia:ot_gps	/Jaskinia Mietusia Wyznia

#fix	MnichStudniaWyz:0	E19.9296361116	N49.2432388811	1685.00m
#flag	MnichStudniaWyz:0	/Mnichowa Studnia Wyznia
#flag	MnichStudniaWyz:0	/ENTRANCE
#note	MnichStudniaWyz:0	/Mnichowa Studnia Wyznia

#fix	Mrozna:0	E19.8671944041	N49.2496944365	1112.20m
#flag	Mrozna:0	/Jaskinia Mrozna
#flag	Mrozna:0	/ENTRANCE
#note	Mrozna:0	/Jaskinia Mrozna

#fix	NadBeczka:0	E19.8837300523	N49.2338799612	1450.00m
#flag	NadBeczka:0	/Jaskinia nad Beczka
#flag	NadBeczka:0	/ENTRANCE
#note	NadBeczka:0	/Jaskinia nad Beczka

#fix	NadPercia:0	E19.8740100498	N49.2366299956	1240.00m
#flag	NadPercia:0	/Jaskinia nad Percia
#flag	NadPercia:0	/ENTRANCE
#note	NadPercia:0	/Jaskinia nad Percia

#fix	NovaKresanica:nvk0	E19.9141877888	N49.2291884063	2016.00m
#flag	NovaKresanica:nvk0	/Nova Kresanica
#flag	NovaKresanica:nvk0	/ENTRANCE
#note	NovaKresanica:nvk0	/Nova Kresanica

#fix	ObcasnaVyv:o1	E19.9298694255	N49.2266111028	1453.00m
#flag	ObcasnaVyv:o1	/Obcasna Vyvieracka
#flag	ObcasnaVyv:o1	/ENTRANCE
#note	ObcasnaVyv:o1	/Obcasna Vyvieracka

#fix	Pawlikowskiego:Mylna:0	E19.8622047217	N49.2393861277	1098.00m
#flag	Pawlikowskiego:Mylna:0	/Mylna
#flag	Pawlikowskiego:Mylna:0	/ENTRANCE
#note	Pawlikowskiego:Mylna:0	/Mylna

#fix	Pawlikowskiego:Oblazkowa:0.0	E19.8625797302	N49.2395616350	1096.62m
#flag	Pawlikowskiego:Oblazkowa:0.0	/Oblazkowa
#flag	Pawlikowskiego:Oblazkowa:0.0	/ENTRANCE
#note	Pawlikowskiego:Oblazkowa:0.0	/Oblazkowa

#fix	Pawlikowskiego:Raptawicka:1.0	E19.8622197642	N49.2398675351	1141.31m
#flag	Pawlikowskiego:Raptawicka:1.0	/Raptawicka
#flag	Pawlikowskiego:Raptawicka:1.0	/ENTRANCE
#note	Pawlikowskiego:Raptawicka:1.0	/Raptawicka

#fix	PodProgiem:0	E19.9136361509	N49.2453167052	1746.62m
#flag	PodProgiem:0	/Jaskinia pod Progiem
#flag	PodProgiem:0	/ENTRANCE
#note	PodProgiem:0	/Jaskinia pod Progiem

#fix	PodZamkiem:0	E19.8647300054	N49.2376580211	1186.00m
#flag	PodZamkiem:0	/Jaskinia Pod Zamkiem
#flag	PodZamkiem:0	/ENTRANCE
#note	PodZamkiem:0	/Jaskinia Pod Zamkiem

#fix	PoszukiwaczySkarbow:0	E19.8660109420	N49.2369970203	1211.00m
#flag	PoszukiwaczySkarbow:0	/Jaskinia Poszukiwaczy Skarbow
#flag	PoszukiwaczySkarbow:0	/ENTRANCE
#note	PoszukiwaczySkarbow:0	/Jaskinia Poszukiwaczy Skarbow

#fix	PrzyJedrusiowej:pj0	E19.9241054868	N49.2415694867	1562.01m
#flag	PrzyJedrusiowej:pj0	/Przy Jedrusiowej Dziurze
#flag	PrzyJedrusiowej:pj0	/ENTRANCE
#note	PrzyJedrusiowej:pj0	/Przy Jedrusiowej Dziurze

#fix	PrzyPrzechodzie:jp0	E19.9240666154	N49.2414805193	1583.50m
#flag	PrzyPrzechodzie:jp0	/Przy Przechodzie
#flag	PrzyPrzechodzie:jp0	/ENTRANCE
#note	PrzyPrzechodzie:jp0	/Przy Przechodzie

#fix	PtasiaStudnia:a14	E19.9056625398	N49.2404085327	1574.74m
#flag	PtasiaStudnia:a14	/Lodowa Litworowa
#flag	PtasiaStudnia:a14	/ENTRANCE
#note	PtasiaStudnia:a14	/Lodowa Litworowa

#fix	PtasiaStudnia:a22	E19.9053213386	N49.2404304870	1516.86m
#flag	PtasiaStudnia:a22	/Jaskinia nad Dachem
#flag	PtasiaStudnia:a22	/ENTRANCE
#note	PtasiaStudnia:a22	/Jaskinia nad Dachem

#fix	PtasiaStudnia:A7	E19.9058563379	N49.2403052113	1591.72m
#flag	PtasiaStudnia:A7	/Jaskinia nad Lodowa Litworowa
#flag	PtasiaStudnia:A7	/ENTRANCE
#note	PtasiaStudnia:A7	/Jaskinia nad Lodowa Litworowa

#fix	PtasiaStudnia:b1	E19.9050577171	N49.2396838823	1627.00m
#flag	PtasiaStudnia:b1	/Ptasia Studnia
#flag	PtasiaStudnia:b1	/ENTRANCE
#note	PtasiaStudnia:b1	/Ptasia Studnia

#fix	RuraPrzyOknie:0	E19.8706939379	N49.2360280272	1210.00m
#flag	RuraPrzyOknie:0	/Rura przy Oknie
#flag	RuraPrzyOknie:0	/ENTRANCE
#note	RuraPrzyOknie:0	/Rura przy Oknie

#fix	SchronPodJedrus:spj0	E19.9238999541	N49.2415694613	1569.05m
#flag	SchronPodJedrus:spj0	/Schron pod Jedrusiowa Dziura
#flag	SchronPodJedrus:spj0	/ENTRANCE
#note	SchronPodJedrus:spj0	/Schron pod Jedrusiowa Dziura

#fix	SmoczaJama:0	E19.8677340137	N49.2378399802	1120.00m
#flag	SmoczaJama:0	/Smocza Jama
#flag	SmoczaJama:0	/ENTRANCE
#note	SmoczaJama:0	/Smocza Jama

#fix	SnieznaStudnia:ss0	E19.9226916000	N49.2414694129	1756.63m
#flag	SnieznaStudnia:ss0	/Sniezna Studnia
#flag	SnieznaStudnia:ss0	/ENTRANCE
#note	SnieznaStudnia:ss0	/Sniezna Studnia

#fix	SpiacychRycerzy:1	E19.9234167324	N49.2499055532	1397.80m
#flag	SpiacychRycerzy:1	/Jaskinia Spiacych Rycerzy
#flag	SpiacychRycerzy:1	/ENTRANCE
#note	SpiacychRycerzy:1	/Jaskinia Spiacych Rycerzy

#fix	StudniaNaSzlaku:0	E19.9132194628	N49.2443194160	1799.50m
#flag	StudniaNaSzlaku:0	/Studnia na Szlaku
#flag	StudniaNaSzlaku:0	/ENTRANCE
#note	StudniaNaSzlaku:0	/Studnia na Szlaku

#fix	StudniaPrzyPrzech:spp0	E19.9240388627	N49.2414805307	1610.42m
#flag	StudniaPrzyPrzech:spp0	/Studnia przy Przechodzie
#flag	StudniaPrzyPrzech:spp0	/ENTRANCE
#note	StudniaPrzyPrzech:spp0	/Studnia przy Przechodzie

#fix	StudniaWKazalnicy:SwK0	E19.9015167179	N49.2400528106	1545.00m
#flag	StudniaWKazalnicy:SwK0	/Studnia w Kazalnicy
#flag	StudniaWKazalnicy:SwK0	/ENTRANCE
#note	StudniaWKazalnicy:SwK0	/Studnia w Kazalnicy

#fix	Swistacza:24	E19.9300494902	N49.2392600572	1802.35m
#flag	Swistacza:24	/Jaskinia Swistacza
#flag	Swistacza:24	/ENTRANCE
#note	Swistacza:24	/Jaskinia Swistacza

#fix	SzaraStudnia:0	E19.9123721817	N49.2441361198	1737.00m
#flag	SzaraStudnia:0	/Szara Studnia
#flag	SzaraStudnia:0	/ENTRANCE
#note	SzaraStudnia:0	/Szara Studnia

#fix	SzczelinaMietusia:0	E19.9025137432	N49.2398780602	1570.00m
#flag	SzczelinaMietusia:0	/Szczelina Mietusia
#flag	SzczelinaMietusia:0	/ENTRANCE
#note	SzczelinaMietusia:0	/Szczelina Mietusia

#fix	SzczelinaNadLejem:0	E20.0575560156	N49.2491669675	1761.00m
#flag	SzczelinaNadLejem:0	/Szczelina nad Lejem
#flag	SzczelinaNadLejem:0	/ENTRANCE
#note	SzczelinaNadLejem:0	/Szczelina nad Lejem

#fix	SzczelinaNadTomI:0	E19.9034100388	N49.2296399901	2065.00m
#flag	SzczelinaNadTomI:0	/Szczelina nad Tomanowa I
#flag	SzczelinaNadTomI:0	/ENTRANCE
#note	SzczelinaNadTomI:0	/Szczelina nad Tomanowa I

#fix	SzczelinaNadTomII:0	E19.9032699725	N49.2297500246	2050.00m
#flag	SzczelinaNadTomII:0	/Szczelina nad Tomanowa II
#flag	SzczelinaNadTomII:0	/ENTRANCE
#note	SzczelinaNadTomII:0	/Szczelina nad Tomanowa II

#fix	Uplazkowa:ju0	E19.9225249917	N49.2416000024	1689.57m
#flag	Uplazkowa:ju0	/Uplazkowa
#flag	Uplazkowa:ju0	/ENTRANCE
#note	Uplazkowa:ju0	/Uplazkowa

#fix	WielkaSniezna:Ciag:0	E19.9209439859	N49.2393398843	1875.25m
#flag	WielkaSniezna:Ciag:0	/Nad Kotliny
#flag	WielkaSniezna:Ciag:0	/ENTRANCE
#note	WielkaSniezna:Ciag:0	/Nad Kotliny

#fix	WielkaSniezna:Ciag:s68	E19.9264416040	N49.2401833406	1689.20m
#flag	WielkaSniezna:Ciag:s68	/Sniezna
#flag	WielkaSniezna:Ciag:s68	/ENTRANCE
#note	WielkaSniezna:Ciag:s68	/Sniezna

#fix	WielkaSniezna:Jasna:j0	E19.9213194362	N49.2396055191	1852.00m
#flag	WielkaSniezna:Jasna:j0	/Jasny Awen
#flag	WielkaSniezna:Jasna:j0	/ENTRANCE
#note	WielkaSniezna:Jasna:j0	/Jasny Awen

#fix	WielkaSniezna:Litworowa:LT58	E19.9147971919	N49.2385638317	1903.00m
#flag	WielkaSniezna:Litworowa:LT58	/Wielka Litworowa
#flag	WielkaSniezna:Litworowa:LT58	/ENTRANCE
#note	WielkaSniezna:Litworowa:LT58	/Wielka Litworowa

#fix	WielkiejTurni:0	E19.9204167053	N49.2449110702	1826.88m
#flag	WielkiejTurni:0	/Jaskinia w Wielkiej Turni
#flag	WielkiejTurni:0	/ENTRANCE
#note	WielkiejTurni:0	/Jaskinia w Wielkiej Turni

#fix	WilczySchron:wsn0	E19.9241805255	N49.2413027503	1635.04m
#flag	WilczySchron:wsn0	/Wilczy Schron
#flag	WilczySchron:wsn0	/ENTRANCE
#note	WilczySchron:wsn0	/Wilczy Schron

#fix	Wysoka7Progow:W-300	E19.8845279749	N49.2337721673	1501.11m
#flag	Wysoka7Progow:W-300	/ENTRANCE
#note	Wysoka7Progow:W-300	/Wysoka Gorny Otwor

; source: unknown - GNSS
#fix	Wysoka7Progow:W7-0	E19.88454604	N49.23364130	1486.69m
#flag	Wysoka7Progow:W7-0	/Otwor
#flag	Wysoka7Progow:W7-0	/Wysoka-Za7 Progami
#flag	Wysoka7Progow:W7-0	/ENTRANCE
#note	Wysoka7Progow:W7-0	/Wysoka-Za7 Progami

#fix	Wysoka7Progow:W7-200	E19.8844058945	N49.2336423527	1482.73m
#flag	Wysoka7Progow:W7-200	/ENTRANCE
#note	Wysoka7Progow:W7-200	/Za7Progami Dolny Otwor

#fix	Wysoka7Progow:W7-500	E19.8844792422	N49.2336792230	1490.96m
#flag	Wysoka7Progow:W7-500	/ENTRANCE
#note	Wysoka7Progow:W7-500	/Za7Progami Gorny Otwor

#fix	WyzKoszowaDziura:0	E20.0586939767	N49.2487219776	1800.00m
#flag	WyzKoszowaDziura:0	/Wyznia Koszowa Dziura
#flag	WyzKoszowaDziura:0	/ENTRANCE
#note	WyzKoszowaDziura:0	/Wyznia Koszowa Dziura

#fix	ZaspalkowaSzczel:zss0	E19.9278111700	N49.2385471910	1743.30m
#flag	ZaspalkowaSzczel:zss0	/Zaspalkowa
#flag	ZaspalkowaSzczel:zss0	/ENTRANCE
#note	ZaspalkowaSzczel:zss0	/Zaspalkowa

#fix	ZawaliskawaTom:0	E19.8955799872	N49.2293299754	1757.00m
#flag	ZawaliskawaTom:0	/Jaskinia Zawaliskowa Tomanowa
#flag	ZawaliskawaTom:0	/ENTRANCE
#note	ZawaliskawaTom:0	/Jaskinia Zawaliskowa Tomanowa

#fix	ZawalonySchron:0	E19.9132329752	N49.2453939621	1790.00m
#flag	ZawalonySchron:0	/Zawalony Schron
#flag	ZawalonySchron:0	/ENTRANCE
#note	ZawalonySchron:0	/Zawalony Schron

#fix	ZbojeckaDziura:0	E19.8117309682	N49.2477690042	1143.00m
#flag	ZbojeckaDziura:0	/Zbojecka Dziura
#flag	ZbojeckaDziura:0	/ENTRANCE
#note	ZbojeckaDziura:0	/Zbojecka Dziura

#fix	ZbojnickaPiwnica:0	E19.8652800413	N49.2364299623	1250.00m
#flag	ZbojnickaPiwnica:0	/Zbojnicka Piwnica
#flag	ZbojnickaPiwnica:0	/ENTRANCE
#note	ZbojnickaPiwnica:0	/Zbojnicka Piwnica

#fix	ZbojnickaTurnia:0	E19.8652800413	N49.2364299623	1260.00m
#flag	ZbojnickaTurnia:0	/Jaskinia w Zbojnickiej Turni
#flag	ZbojnickaTurnia:0	/ENTRANCE
#note	ZbojnickaTurnia:0	/Jaskinia w Zbojnickiej Turni

#fix	Ziobrowa:0	E19.8637939915	N49.2389060292	1104.00m
#flag	Ziobrowa:0	/Jaskinia Ziobrowa
#flag	Ziobrowa:0	/ENTRANCE
#note	Ziobrowa:0	/Jaskinia Ziobrowa

#fix	Ziobrowa:5.24	E19.8636112906	N49.2385939771	1106.01m
#flag	Ziobrowa:5.24	/Jaskinia pod Niznia Zbojnicka Turnia
#flag	Ziobrowa:5.24	/ENTRANCE
#note	Ziobrowa:5.24	/Jaskinia pod Niznia Zbojnicka Turnia

#fix	Zoska:0	E19.9146609888	N49.2449980041	1790.00m
#flag	Zoska:0	/Jaskinia Zoska
#flag	Zoska:0	/ENTRANCE
#note	Zoska:0	/Jaskinia Zoska

#fix	Zoska:1Z	E19.9148025272	N49.2450159755	1785.84m
#flag	Zoska:1Z	/Zagonna Studnia
#flag	Zoska:1Z	/ENTRANCE
#note	Zoska:1Z	/Zagonna Studnia

#fix	Zwolinskiego:0	E19.9772778459	N49.2511666731	1314.00m
#flag	Zwolinskiego:0	/Zwolinskiego
#flag	Zwolinskiego:0	/ENTRANCE
#note	Zwolinskiego:0	/Zwolinskiego
