#[
CAVE_ID			"T.E-12.59"
CAVE_NAME		"Zawalony Schron"
SURVEY_ID		ZAWSCH
SURVEY_NAME		"Zawalony Schron"
UPDATE_DATE		2026-02-24
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
DATA_SOURCE		"Z. Tabaczynski"
LICENSE			"http://creativecommons.org/licenses/by-sa/2.0/"

TEAM "M. Parczewski, Z. Tabaczynski"
INSTRUMENT "Topo-Vulcan"
#]

#prefix zawsch
#date 1999-10-30
#units meters order=DAV
#units A=D V=D

;Zawalony Schron

0	1	3.85	180	-10
1	2	2.15	266	0
1	3	2.15	86	0
