#[
CAVE_ID         "WPJ:SNASZ"
CAVE_NAME       "Studnia na Szlaku"
SURVEY_ID       "STNASZ1"
SURVEY_NAME     "Studnia na Szlaku"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "nieznane"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

#units meters order=DAV
#units A=D V=D
; Brak daty w aktywnych i _RAW; DECL zachowuje dotychczasowa orientacje Cavern.
#Units DECL=0.819D
#prefix StudniaNaSzlaku
;TODO #date
;Z. Tabaczynski
; Otwor w tym pliku: StudniaNaSzlaku:0 - fix/flag/note w Poligony/OTWORY.SRV
0	1	5	270	-89
