"Jaskinie Tatrzanskie" - v.0.09

Historia wersji:
v.0.00  (rok 2010-2011)  - projekt wstepny, brak koordynatora, dane haotyczne
v.0.01 (24.04.2012) - zmieniono drzewko projektu, dodano Wysoka, Bandziocha
v.0.02 (25.04.2012) - ujednolicono sposob wpisania danych, usunieto polskie znaki z plikow
v.0.03 (26.04.2012) - zmieniono uklad drzewka plikow; dodano powierzchnie calosci
v0.04 (04.05.2012) - dodano model terenu oparty o poziomice
v0.05 (14.05.2012) - dodano Jaskinie Mylna
v0.06 (18.10.2013) - przejecie koordynacji - Dariusz Lubomski; dodano ciag pomiarowy w Snieznej - 20130713 - autorzy pomiarow Karol Makowski; Marcin Slowik
v0.07 (04.11.2013) - dodano jaskinie Goryczkowa
v0.08 (13.11.2013) - dodano jaskinie Kalacka, dodano jaskinie Studnia w Kazalnicy, poprawka w Koziej
v0.09 (20.11.2013) - dodano jaskinie Zwolinskiego, dodano jaskinie Swistacza(brak wspolrzednych GPS), nowe pomiary Koprowej Studni






---------------------------------------------------------------------------------------------------------------------------------------------------------
Projekt "Jaskinie Tatrzanskie" ma celu zebranie jak najwiecej
danych kartograficznych w jednym miejscu.
Ma to byc pomocne nam obecnie dzialajacym w jaskiniach tatrzanskich,
ale przede wszystkim ma to byc tez dla kolejnych pokolen.
W tym jednym projekcie chcemy zebrac dane pomiarowe jaskin, dane terenowe,
sciezki dojscia, plany, przekroje i inne wazne informacje.
---------------------------------------------------------------------------------------------------------------------------------------------------------
!! WAZNE !! ABY ZACHOWAC LAD I PORZADEK, PROSZE ABY WSZYSCY DZIALAJACY CZYNNIE W PROJEKCIE
NOWE DANE PRZESYLALI DO KOORDYNATORA. ON PO ICH WPROWADZENIU ROZESLE POPRAWIONY PROJEKT
DO WSZYSTKICH ZAINTERESOWANYCH. ZACHOWAMY WTEDY JEDNOLITOSC
---------------------------------------------------------------------------------------------------------------------------------------------------------
* nowy koordynator projektu: Dariusz Lubomski (SKTJ)
* koordynator projektu: Krzysztof "chomik" Borgiel (SBB)
* konsultacje i wsparcie: Piotr "Kierownik" Stelmach (WKTJ)
* przygotowanie Numerycznego Modelu Terenu: Jacek "Maly" Szczygiel (KKS)
---------------------------------------------------------------------------------------------------------------------------------------------------------
* osoby, których dane pomiarowe sa obecnie w projekcie (dziekujemy im za ich prace):
Czeslaw Szura
Artur Zera
Alan Zera
Jakub Pysz
Jacek Szczygiel
Piotr Stelmach
Dariusz Bartoszewski
Filip Filar
Karol Makowski; Marcin Slowik
Peter Imrich; Tina Majerníèková; Jan Šmoll; Krysztof Dudzinski; Gabika Majerníèková; Juraj Szunyog
Krysztof Dudzinski; Tomasz Kozica-Zwijacz
Krysztof Dudzinski; Zbigniew Tabaczynski
Emanuel Soja; Jacek Szczygiel, M. Rembecki