"Jaskinie Tatrzanskie" - v.0.15

Historia wersji:
v0.00  (rok 2010-2011)  - projekt wstepny, brak koordynatora, dane haotyczne
v0.01 (24.04.2012) - zmieniono drzewko projektu, dodano Wysoka, Bandziocha
v0.02 (25.04.2012) - ujednolicono sposob wpisania danych, usunieto polskie znaki z plikow
v0.03 (26.04.2012) - zmieniono uklad drzewka plikow; dodano powierzchnie calosci
v0.04 (04.05.2012) - dodano model terenu oparty o poziomice
v0.05 (14.05.2012) - dodano jaskinie Mylna
v0.06 (18.10.2013) - przejecie koordynacji - Dariusz Lubomski; dodano ciag pomiarowy w Snieznej - 20130713 - autorzy pomiarow Karol Makowski; Marcin Slowik
v0.07 (04.11.2013) - dodano jaskinie Goryczkowa
v0.08 (13.11.2013) - dodano jaskinie Kalacka, dodano jaskinie Studnia w Kazalnicy, poprawka w Koziej
v0.09 (20.11.2013) - dodano jaskinie Zwolinskiego, dodano jaskinie Swistacza(brak wsp GPS), nowe pomiary Koprowej Studni
v0.10 (24.11.2013) - dodano system Zoska - Zagonna Studnia
v0.11 (27.11.2013) - Coordinates UTM/UPS grid-relative; Declinations Derive from #DATE
v0.12 (02.12.2013) - dodano jaskinie Harda (ciag glowny), dodano jaskinie Kamienne Mleko, dodano jaskinie Dmuchawa(brak wsp GPS), zrobiono porzadek w nazwiskach
		     ponizej wypisane sa osoby ktore bezposrednio wsparly projekt, zas nazwiska kartujacych wypisane sa w plikach poszczegolnych sesji pomiarowych
v0.13 (08.12.2013) - dodano jaskinie Spiacych Rycerzy (fragment), Jaskinia Lodowa Mietusia, Szczelina Mietusia, Zbójecka Dziura, Szczelina nad Tomanowa II (brak wsp GPS),
		     Szczelina nad Tomanowa I (brak wsp GPS), Dziura w Stole (brak wsp GPS), Jaskinia Zawaliskowa Tomanowa (brak wsp GPS), Jaskinia Poszukiwaczy Skarbow (fragment)
		     Jaskinia Pod Zamkiem(fragment), Jaskinia w Zbójnickiej Turni (brak wsp GPS), Zbójnicka Piwnica (brak wsp GPS), Jaskinia Ziobrowa i Jaskinia pod Niznia Zbojnicka Turnia,
		     Jaskinia Ciepla (brak wsp GPS), Gawra, Rura przy Oknie (brak wsp GPS), Lustrzany Korytarz (brak wsp GPS), Jaskinia nad Percia (brak wsp GPS), Jaskinia nad Beczka (brak wsp GPS),
		     Ponad to dodano ciag powierzchniowy od Koprowej Studni do Jaskini Swistaczej
v0.14 (04.04.2014) - Z http://geoportal.pgi.gov.pl dodano wpolrzedne dla jaskin : Dmuchawa, Jaskinia nad Beczka, Jaskinia nad Percia, Lustrzany Korytarz, Rura przy Oknie, Jaskinia Ciepla, Jaskinia w Zbojnickiej Turni,
		      Zbojnicka Piwnica, Dziura w Stole, Jaskinia Zawaliskowa Tomanowa, Szczelina nad Tomanowa I, Szczelina nad Tomanowa II
v0.15 (21.04.2014) - Dodano Jaskinie Biala, Szara Studnia, Jaskinia w Wielkiej Turni, Czerwona Studzienka, Dziurka w Trawce. Drobne aktualizacje wspolrzednych i wysokosci.
---------------------------------------------------------------------------------------------------------------------------------------------------------
Projekt "Jaskinie Tatrzanskie" ma celu zebranie jak najwiecej
danych kartograficznych w jednym miejscu.
Ma to byc pomocne nam obecnie dzialajacym w jaskiniach tatrzanskich,
ale przede wszystkim ma to byc tez dla kolejnych pokolen.
W tym jednym projekcie chcemy zebrac dane pomiarowe jaskin, dane terenowe,
sciezki dojscia, plany, przekroje i inne wazne informacje.
---------------------------------------------------------------------------------------------------------------------------------------------------------
!! WAZNE !! ABY ZACHOWAC LAD I PORZADEK, PROSZE ABY WSZYSCY DZIALAJACY CZYNNIE W PROJEKCIE
NOWE DANE PRZESYLALI DO KOORDYNATORA. ON PO ICH WPROWADZENIU ROZESLE POPRAWIONY PROJEKT
DO WSZYSTKICH ZAINTERESOWANYCH. ZACHOWAMY WTEDY JEDNOLITOSC
---------------------------------------------------------------------------------------------------------------------------------------------------------
* nowy koordynator projektu: Dariusz Lubomski (SKTJ)
* koordynator projektu: Krzysztof "Chomik" Borgiel (SBB)
* konsultacje i wsparcie: Piotr "Kierownik" Stelmach (WKTJ)
* przygotowanie Numerycznego Modelu Terenu: Jacek "Maly" Szczygiel (KKS)
---------------------------------------------------------------------------------------------------------------------------------------------------------
* osoby ktore bezposrednio wsparly projekt (dziekujemy im za ich prace):

Czeslaw Szura
Artur Zera
Alan Zera
Jakub Pysz
Jacek Szczygiel
Piotr Stelmach
Dariusz Bartoszewski
Filip Filar
Karol Makowski
Krysztof Dudzinski
Emanuel Soja
Pawel Ramatowski
Jakub Nowak
Rafal Klimara
Piotr Sienkiewicz
Zbigniew Tabaczynski
