#[
CAVE_ID			"T.D-04.01"
CAVE_NAME		"Zbojecka Dziura"
UPDATE_DATE		2026-03-07
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
REFERENCE_SYSTEM	"WGS84"
COORDINATE_SYSTEM	"UTM"
DATA_SOURCE		"Panstwowy Instytut Geologiczny"
LICENSE			"http://creativecommons.org/licenses/by-sa/4.0/"
#]

#prefix zbdziu
#flag	0	/Zbojecka Dziura
#note	0	/Zbojecka Dziura
#fix	0	E19.811731	N49.247769	1143.0m
