#units meters order=DAV
#prefix lukor
#note	0	/Lustrzany Korytarz
#flag	0	/Lustrzany Korytarz
#date 2006-08-26
#FIX  0   E19:52:42.060  N49:14:15.108   1530.0m
;team J. Nowak, J. Matras
;Wys. nad dnem wawozu ok. 360 m
0	1	3.8	20	48
1	2	11.2	125	45
