#[
CAVE_ID			"T.F-11.22"
CAVE_NAME		"Szczelina nad Tomanowa II"
SURVEY_ID		SZNDT2
SURVEY_NAME		"Szczelina nad Tomanowa II"
UPDATE_DATE		2026-03-07
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
DATA_SOURCE		"J. Nowak"
LICENSE			"http://creativecommons.org/licenses/by-sa/4.0/"

TEAM "J. Nowak"
INSTRUMENT "nieznany"
#]

#prefix SzczelinaNadTomII
#date 2008-10-18
#units meters order=DAV
#units A=D V=D

;Wys. nad dnem Doliny Tomanowej: ok. 480 m

0	1	3.90	118	-40
1	2	2.70	115	-70
2	3	3.00	102	-10
3	4	2.50	115	0
