#[
CAVE_ID         "T.F-11.21"
CAVE_NAME       "Szczelina nad Tomanowa I"
SURVEY_ID       "SZNDT1"
SURVEY_NAME     "Szczelina nad Tomanowa I"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "Dariusz Lubomski"
COORDINATOR_EMAIL "darek.lubomski@gmail.com"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "J. i J. Nowak"
INSTRUMENT      "nieznane"
SURVEY_DATE     "2008-10-18"
SURVEY_GRADE    "nieznane"
PROCESSING      "zachowano istniejacy aktywny plik SRV"
#]

#prefix SzczelinaNadTomI
#date 2008-10-18
#units meters order=DAV
#units A=D V=D

;Wys. nad dnem Doliny Tomanowej: ok. 500 m

; Otwor w tym pliku: SzczelinaNadTomI:0 - fix/flag/note w Poligony/OTWORY.SRV
0	1	3.25	84	35
1	2	4.80	145	-20

1	1.1	5.80	0	-90
