#[
CAVE_ID         "T.E-09.12"
CAVE_NAME       "Jaskinia Czarna"
SURVEY_ID       "GL_N1"
SURVEY_NAME     "Ustawienie poczatku Kujata - zalozenie przegladowe"
UPDATE_DATE     "2026-09-17"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "Dariusz Lubomski"
COORDINATOR_EMAIL "darek.lubomski@gmail.com"
SOURCE_REF      "_RAW/02"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "nieznane"
SURVEY_GRADE    "nieznane"
PROCESSING      "Zalozenie K0 przy glownym otworze dla nakladki; brak zmierzonego domiaru i drugiego dowiazania; patrz DWA_CIAGI.md"
#]

; ZALOZENIE PRZEGLADOWE: CiagSkany:0 ustawiony przy GNSS glownego otworu.
; Dziennik opisuje K0 jako Otwor, ale nie dokumentuje domiaru do punktu GNSS.
; Zerowy wektor sluzy nakladce do oceny, nie potwierdza tozsamosci stanowisk.
; Jest to jedyne polaczenie nowego ciagu z obecna siecia. Nie tworzy petli.
; Brak nawiazania do III otworu; K76 to Koniec Colorado. Patrz DWA_CIAGI.md.
#prefix2 Czarna
#prefix NawiazanieKujat
#units meters order=DAV
#units A=D V=D DECL=0
M:otwor1 CiagSkany:0 0 0 0
#note CiagSkany:0 /Kujat K0: ustawienie przy otworze jest zalozeniem do oceny
