#[
CAVE_ID         "T.E-09.12"
CAVE_NAME       "Jaskinia Czarna"
SURVEY_ID       "GL_P1"
SURVEY_NAME     "HIPOTEZA Kujat 74 = Borowiec 70 - dojscie do III otworu"
UPDATE_DATE     "2026-09-19"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "Dariusz Lubomski"
COORDINATOR_EMAIL "darek.lubomski@gmail.com"
SOURCE_REF      "_RAW/02"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "nieznane"
SURVEY_GRADE    "nieznane"
PROCESSING      "Hipoteza K74=B70=dawny Kujat13 na polecenie uzytkownika; list potwierdza tylko B70=dawny K13; wspolny punkt nowego dziennika niepotwierdzony; osobny plik do wylaczenia"
#]

; HIPOTEZA POLACZENIA DO OCENY - polecenie uzytkownika 2026-09-19.
; Przyjeto CiagSkany:74 = Borowiec:70 = dawny Kujat:13.
; List Kujata potwierdza TYLKO ostatnia rownosc, nie numer 74 nowego dziennika.
; K74 wybrano przy znanym odejsciu B70 do Sali Bernarda i III otworu:
; bez lacznika przy D39-40=12.20: K74-B70 to 2.54 m 3D, K70-B70 to 70.78 m.
; Dalszy ciag K74-76 i B70-73 biegnie do Colorado. Numeracje nie sa identyczne.
; Bliskosc geometryczna nie dowodzi tozsamosci; brak szkicu wspolnego punktu.
; Zero oznacza ZALOZONE utozsamienie, nie zmierzony domiar 0 m ani 2.54 m.
; Laczy oba ciagi, tworzy petle i zmienia wyrownanie istniejacej sieci.
; Wylacz ten osobny plik w WPJ, aby wrocic do wariantu bez polaczenia.
; Warunkowe niezamkniecia i kontrola wplywu: DWA_CIAGI.md i skrypt audytu.
#prefix2 Czarna
#prefix LaczenieKujat
#units meters order=DAV
#units A=D V=D DECL=0
CiagSkany:74 Borowiec:70 0 0 0
#note CiagSkany:74 /HIPOTEZA K74=B70=dawny K13; niepotwierdzona tozsamosc punktow
