#[
CAVE_ID			"T.E-09.12"
CAVE_NAME		"Jaskinia Czarna"
UPDATE_DATE		2026-03-10
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
REFERENCE_SYSTEM	"WGS84"
COORDINATE_SYSTEM	"UTM"
DATA_SOURCE		"Panstwowy Instytut Geologiczny"
LICENSE			"http://creativecommons.org/licenses/by-sa/4.0/"
#]

#prefix czarna
#flag	otwor1	/Jaskinia Czarna
#flag	otwor1	/ENTRANCE
#note	otwor1	/Jaskinia Czarna
#fix	otwor1	E19.87037222	N49.24438611	1326.0m
