#[
CAVE_ID			"unknown"
CAVE_NAME		"Jaskinia Oblazkowa"
UPDATE_DATE		2026-02-12
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
REFERENCE_SYSTEM	"WGS84"
COORDINATE_SYSTEM	"UTM"
DATA_SOURCE		"Polskie Towarzystwo Przyjaciol Nauk o Ziemi"
LICENSE			"http://creativecommons.org/licenses/by-sa/2.0/"

TEAM  "unknown"
INSTRUMENT "unknown"
#]

#UNITS meters order=dav
#Units A=D V=D
#prefix OBLAZK
#note	0.0	/Oblazkowa
#flag	0.0	/Oblazkowa
#fix	0.0	417205.0875	5454709.36	1097
