#[
CAVE_ID			"T.E-08.05"
CAVE_NAME		"Jaskinia Oblazkowa"
UPDATE_DATE		2026-02-12
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
REFERENCE_SYSTEM	"WGS84"
COORDINATE_SYSTEM	"UTM"
DATA_SOURCE		"Panstwowy Instytut Geologiczny, F. Filar"
LICENSE			"http://creativecommons.org/licenses/by-sa/2.0/"
#]

#prefix OBLAZ
#flag	0.0	/Oblazkowa
#note	0.0	/Oblazkowa

