#[
CAVE_ID         "WPJ:ZASPALKS"
CAVE_NAME       "Zaspalkowa Szczelina"
SURVEY_ID       "ZASSZC"
SURVEY_NAME     "Zaspalkowa Szczelina"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "nieznane"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

#prefix ZaspalkowaSzczel
;Zaspalkowa Szczelina
#Units Meters Order=dav
; Brak daty w aktywnych i _RAW; DECL zachowuje dotychczasowa orientacje Cavern.
#Units DECL=0.819D
; Otwor w tym pliku: ZaspalkowaSzczel:zss0 - fix/flag/note w Poligony/OTWORY.SRV
zss0 	zss1 	4.42 	215.82 	-26.87 ; pomiar powtorzony w ZASSZC.SRV:8
zss1 	zss2 	4.71 	184.48	-38.00
;zss0 	zss1 	4.42 	215.82 	-26.87 ; pomiar powtorzony w ZASSZC.SRV:6
zss1 	zss3 	3.60 	248.48 	33.57
zss3 	zss4 	2.50 	0.00 	90.00
