#[
CAVE_ID         "WPJ:NK"
CAVE_NAME       "Nova Kresanica"
SURVEY_ID       "KOM"
SURVEY_NAME     "20 m komin"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "2007-01-03"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

#units meters order=AVD
#units A=D V=D
#date 2007-01-03
;TODO data prawdopodobnie bledna
;TODO brak info kto mierzyl
#prefix NovaKresanica
nvk123	nvk124	78.00	-16.00	3.17	<1.00,1.20,0.00,0.60>
nvk124	nvk125	135.00	13.00	1.60	<1.10,20.00,1.30,0.00>
nvk125	nvk126	0.00	-90.00	19.47	<20.00,0.00,4.00,1.00>
nvk126	nvk103	42.50	15.50	5.31	<5.00,1.00,1.60,0.80>
