#[
CAVE_ID         "WPJ:WILCZSCH"
CAVE_NAME       "Wilczy Schron"
SURVEY_ID       "WILSCH"
SURVEY_NAME     "Wilczy Schron"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "nieznane"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

#prefix WilczySchron
;Wilczy Schron
#Units Meters Order=dav
; Brak daty w aktywnych i _RAW; DECL zachowuje dotychczasowa orientacje Cavern.
#Units DECL=0.819D
; Otwor w tym pliku: WilczySchron:wsn0 - fix/flag/note w Poligony/OTWORY.SRV
wsn0 	wsn1 	2.66 	169.33	 6.26
wsn1 	wsn2 	3.35 	84.81 	-8.41
