#[
CAVE_ID         "WPJ:SCHPJEDR"
CAVE_NAME       "Schron Pod Jedrusiowa"
SURVEY_ID       "SCHJED"
SURVEY_NAME     "Schron pod Jedrusiowa"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "nieznane"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

#prefix SchronPodJedrus
#Units Meters Order=dav
; Brak daty w aktywnych i _RAW; DECL zachowuje dotychczasowa orientacje Cavern.
#Units DECL=0.819D
; Otwor w tym pliku: SchronPodJedrus:spj0 - fix/flag/note w Poligony/OTWORY.SRV
spj0 	spj1 	3.55 	225.00 	0.00
spj1 	spj2 	2.55 	90.00 	-11.31
