#[
CAVE_ID         "WPJ:SNIEZNA"
CAVE_NAME       "Wielka Sniezna"
SURVEY_ID       "JASNYA"
SURVEY_NAME     "Jasny Awen"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "nieznane"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

;Jasny Awen
;
;
;
#units order=avd
; Brak daty w aktywnych i _RAW; DECL zachowuje dotychczasowa orientacje Cavern.
#Units DECL=0.819D
#prefix2 WielkaSniezna
#prefix Jasna
; Otwor w tym pliku: WielkaSniezna:Jasna:j0 - fix/flag/note w Poligony/OTWORY.SRV
j0	j1	0	-90	4.10
j1	j2	180	-75	6.00
j2	j3	277	15	7.60
j3	j4	0	-90	1.30
j4	j5	272	4.5	2.88
j5	j6	0	-90	0.10
j6	j7	243	-57	5.45
j7	j8	169	-59	6.50
j8	j9	171	-62	4.58
j9	j10	232	-70	4.08
j10	j11	278	-15	6.34
j11	j12	264	14	3.16
j12	j13	0	-90	13.92
j13	j14	231	5.5	5.00
j14	j15	282	71	5.75
j15	j16	285	39	5.12
j16	j17	252	-60	3.86
j17	j18	189	-73	9.52
j18	j19	0	-90	15.50
j19	j20	17	0	10.30
