#[
CAVE_ID			"T.F-08.06"
CAVE_NAME		"Jaskinia Ciepla"
UPDATE_DATE		2026-03-07
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
REFERENCE_SYSTEM	"WGS84"
COORDINATE_SYSTEM	"UTM"
DATA_SOURCE		"Panstwowy Instytut Geologiczny"
LICENSE			"http://creativecommons.org/licenses/by-sa/2.0/"
#]

#prefix ciepla
#flag	0	/Jaskinia Ciepla
#note	0	/Jaskinia Ciepla
#fix	0	E19.865580	N49.233470	1331.0m
