#[
CAVE_ID			"T.F-08.06"
CAVE_NAME		"Jaskinia Ciepla"
SURVEY_ID		JCIEPLA
SURVEY_NAME		"Jaskinia Ciepla"
UPDATE_DATE		2026-03-07
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
DATA_SOURCE		"J. Nowak"
LICENSE			"http://creativecommons.org/licenses/by-sa/2.0/"

TEAM "J. Nowak, E. Wojcik"
INSTRUMENT "nieznany"
#]

#prefix ciepla
#date 2007-12-01
#units meters order=DAV
#units A=D V=D

0	1	2.90	78	-22
1	2	3.00	17	-17
2	3	3.10	22	27
3	4	1.80	35	-25
4	5	2.85	70	-38
5	6	3.00	152	-50

1	1.1	2.50	110	-25
