#[
CAVE_ID         "WPJ:JWWT"
CAVE_NAME       "Jaskinia w Wielkiej Turni"
SURVEY_ID       "JWWT1"
SURVEY_NAME     "Jaskinia w Wielkiej Turni"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "2001-07-07"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

#units meters order=DAV
#units A=D V=D
#prefix WielkiejTurni
;P. Gruszka i Z. Tabaczynski
#date 2001-07-07
; Otwor w tym pliku: WielkiejTurni:0 - fix/flag/note w Poligony/OTWORY.SRV
0	1	3.65	305	-45
1	2	4.04	205	-87
2	3	1.35	314	-33
3	4	4.56	284	-55
4	5	2.5	16	-53
5	6	3.07	95	-18
