#units meters order=DAV
#units A=D V=D
#prefix WielkiejTurni
;P. Gruszka i Z. Tabaczynski
#date 2001-07-07
; Otwor w tym pliku: WielkiejTurni:0 - fix/flag/note w Poligony/OTWORY.SRV
0	1	3.65	305	-45
1	2	4.04	205	-87
2	3	1.35	314	-33
3	4	4.56	284	-55
4	5	2.5	16	-53
5	6	3.07	95	-18
