#[
CAVE_ID         "WPJ:DZPSWIST"
CAVE_NAME       "Dziura Pod Swistowa"
SURVEY_ID       "DZISWI"
SURVEY_NAME     "Dziura pod Swistowa"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "nieznane"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

#prefix DziuraPodSwist
;Dziura pod Swistowa
#Units Meters Order=dav
; Brak daty w aktywnych i _RAW; DECL zachowuje dotychczasowa orientacje Cavern.
#Units DECL=0.819D
; Otwor w tym pliku: DziuraPodSwist:dps0 - fix/flag/note w Poligony/OTWORY.SRV
dps0 	dps1 	3.15 	341.51 	0.00
