#[
CAVE_ID			"T.E-08.25"
CAVE_NAME		"Jaskinia Ziobrowa"
UPDATE_DATE		2026-03-07
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
REFERENCE_SYSTEM	"WGS84"
COORDINATE_SYSTEM	"UTM"
DATA_SOURCE		"Panstwowy Instytut Geologiczny"
LICENSE			"http://creativecommons.org/licenses/by-sa/4.0/"
#]

#prefix Ziobrowa
#flag	0	/Jaskinia Ziobrowa
#flag	0	/ENTRANCE
#note	0	/Jaskinia Ziobrowa
#flag	5.24	/Jaskinia pod Niznia Zbojnicka Turnia
#flag	5.24	/ENTRANCE
#note	5.24	/Jaskinia pod Niznia Zbojnicka Turnia
#fix	0	E19.863794	N49.238906	1104.0m
