#[
CAVE_ID         "T.E-08.04"
CAVE_NAME       "Jaskinia Mylna"
SURVEY_ID       "ULPAWLCG"
SURVEY_NAME     "Ulica Pawlikowskiego-CG"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "Dariusz Lubomski"
COORDINATOR_EMAIL "darek.lubomski@gmail.com"
SOURCE_REF      "../_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "F. Filar"
INSTRUMENT      "DistoX2"
SURVEY_DATE     "2009-01-01"
SURVEY_GRADE    "nieznane"
PROCESSING      "zachowano istniejacy aktywny plik SRV"
#]

#prefix2 Pawlikowskiego
#prefix Mylna
#date 2009-01-01
#UNITS meters order=dav
#Units A=D V=D

8	200	1.47	173	-6
200	201	5.08	215	-17
201	202	12.55	235	-1
202	203	13.48	243	-1
203	204	11.55	212	2
204	205	3.39	205	-10
205	206	8.18	224	11