#[
CAVE_ID			"T.E-08.73"
CAVE_NAME		"Zbojnicka Piwnica"
SURVEY_ID		ZP
SURVEY_NAME		"Zbojnicka Piwnica"
UPDATE_DATE		2026-03-07
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
DATA_SOURCE		"J. Nowak"
LICENSE			"http://creativecommons.org/licenses/by-sa/4.0/"

TEAM "J. Nowak, J. Slusarczyk"
INSTRUMENT "nieznany"
#]

#prefix ZbojnickaPiwnica
#date 2007-07-15
#units meters order=DAV
#units A=D V=D

;Wys. nad dnem wawozu ok. 140 m

0	1	1.30	0	-90
1	2	2.35	117	0
2	3	4.30	37	-4	;II otwor
3	4	1.15	175	0
4	5	2.70	102	-12
5	6	2.20	340	-25	;III otwor

2	2.1	2.35	0	-90	;dolne pietro
2.1	2.2	2.00	63	-15
2.2	2.3	3.10	103	36
2.3	5	2.05	39	7
