#prefix BandziochKom
#Units Order=DAV
#Units meters
#Units A=D V=D
; Brak daty w aktywnych i _RAW; DECL zachowuje dotychczasowa orientacje Cavern.
#Units DECL=0.819D
;Sala Zwirki
BD015	BD015001	12.8	107	15
