#[
CAVE_ID         "WPJ:BK-C5D"
CAVE_NAME       "Ciag 5 Dna"
SURVEY_ID       "BK-B5D-S"
SURVEY_NAME     "Boki Ciagu 5 Dna - Stopnie"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "1981-07-01"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

#prefix BandziochKom
#Units Order=DAV
#Units meters
#Units A=D V=D
#date 1981-07-01
;Pom S. Kotarba J. Varey 1981
O028       	O028001	2.86	278	32
O028001	O028002	5.99	330	7
O028002	O028003	5.73	8	2
O028003	O028004	3.51	42	5
