#[
CAVE_ID         "WPJ:BK-C3D"
CAVE_NAME       "Ciag 3 Dna"
SURVEY_ID       "BK-B3D-G"
SURVEY_NAME     "Boki Ciagu 3 Dna - Grady"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "nieznane"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

#prefix BandziochKom
#Units Order=DAV
#Units meters
#Units A=G V=G
; Brak daty w aktywnych i _RAW; DECL zachowuje dotychczasowa orientacje Cavern.
#Units DECL=0.819D
;Kolorowa Salka
BDA	BDA001	5.4	147	-42
BDA001	BDA002	6	400	22
BDA002	BDA003	5.4	52	-61
BDA003	BDA004	3.6	378	0
BDA004	BDA005	5.3	359	21
BDA005	BDA006	7.3	331	41
BDA006	BDA007	4.2	300	56

BDA006  	BDA00601	7.5	10	10
