#[
CAVE_ID         "WPJ:BK-C4D"
CAVE_NAME       "Ciag 4 Dna"
SURVEY_ID       "BK-C4D-G"
SURVEY_NAME     "Ciag 4 Dna - Grady"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "nieznane"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

#prefix BandziochKom
#Units Order=DAV
#Units meters
#Units A=G V=G
; Brak daty w aktywnych i _RAW; DECL zachowuje dotychczasowa orientacje Cavern.
#Units DECL=0.819D
M	M001	9.53	130	-39
M001	M002	6.21	129	-55
M002	M003	16.07	157	-59
M003	M004	12.62	123	-25
M004	M005	5.42	93	-15
M005	M006	5.41	135	-39
M006	M007	19.37	116	-37
M007	MA	18.23	113	-51
MA	M009	4.00	137	-26
M009	M010	5.75	182	-29
M010	MB	11.67	134	-42
MB	M012	11.33	189	-8
M012	M013	8.15	119	-18
M013	M014	9.30	112	-42
M014	M015	6.87	108	-45
M015	MC	16.66	114	-62
