#[
CAVE_ID         "WPJ:BK-C4D"
CAVE_NAME       "Ciag 4 Dna"
SURVEY_ID       "BK-C4D-S"
SURVEY_NAME     "Ciag 4 Dna - Stopnie"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "1981-07-01"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

#prefix BandziochKom
#Units Order=DAV
#Units meters
#Units A=D V=D
#date 1981-07-01
#Flag	MC007004
#Note	MC007004	4 Dno
;Pom. J.Orlowski, Z.Gruza, M. Swider 1981
MC	MC001	15.60	76	-34
MC001	MC002	9.00	324	36
MC002	MC003	3.70	27	22
MC003	MC004	3.00	319	67
MC004	MC005	3.60	346	7
MC005	MC006	19.50	0	-90
MC006	MC007	3.20	310	-13
;Nowe 4 Dno
MC007    	MC007001	6.20	297	0
MC007001	MC007002	2.60	0	-90
MC007002	MC007003	17.00	265	-27
MC007003	MC007004	17.30	78	-31
