#[
CAVE_ID         "WPJ:BK-C1D"
CAVE_NAME       "Ciag 1 Dna (Stare Dno)"
SURVEY_ID       "BK-CSD-G"
SURVEY_NAME     "Ciag Starego Dna - Grady"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "1977-05-15"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

#prefix BandziochKom
#Units Order=DAV
#Units meters
#Units A=G V=G
#date 1977-05-15
;Pom. A. Ciszewski, K. Kleszynski 15.05.1977
BA	BB	3.15	398	-88
BB	B025	7.6	131	-51
B025	B026	7.12	174	-37
B026	B027	3.64	190	-15
B027	B028	5.45	161	-11
B028	B029	6.04	216	-62
B029	B030	2.84	166	-26
B030	B031	6.56	220	-29
B031	B032	5.35	87	-52
B032	B033	3.8	210	-35
B033	BC	10.89	123	-69
