Opracowanie: Piotr Stelmach - WKTJ
Na podstawie pomiarów wykonanych  w latach 1976-1989
przez zespoly inwentaryzacyjne Oddzialu Krakowskiego
PTPNoZ pod kierunkiem Wladyslawa Borowca oraz zespoly
inwentaryzacyjne KKTJ i AKSiA

Specjalne podziekowania dla S. Kotarby za udostepniene materialow

Ze wzgledu na ograniczenia programowe
(max 8 znakow do oznaczenia danego punktu)
numeracja zostala zmieniona wedlug nastepujacego schematu

Oznaczenie orginalne - Oznaczenie zastepcze
009          	A
014           	B
014023    	BA
014024   	BB
014034   	BC
014047   	BD
014056   	BE
014023004	BAA
014047013	BDA
018            	C
022          	D
025          	E
025006   	EA
029          	F
030          	G
030011    	GA
030026   	GB
030027   	GC
030011006	GAA
030027012	GCA
033          	H
036          	I
040            	J
042          	K
042003   	KA
050          	L
050012      	LA
050019    	LB
081           	M
081008     	MA
081011   	MB
081016      	MC
083          	N
083001        	NA
097          	O
107          	U
120           	P
