#[
CAVE_ID			"T.D-22.04"
CAVE_NAME		"Szczelina nad Lejem"
UPDATE_DATE		2026-02-24
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
REFERENCE_SYSTEM	"WGS84"
COORDINATE_SYSTEM	"UTM"
DATA_SOURCE		"https://jaskiniepolski.pgi.gov.pl/, Z. Tabaczynski"
LICENSE			"http://creativecommons.org/licenses/by-sa/2.0/"
#]

#prefix sznlej
#flag	0	/Szczelina nad Lejem
#note	0	/Szczelina nad Lejem
#fix	0	E20.057556	N49.249167	1761.0m
