#[
CAVE_ID         "WPJ:CZSTD"
CAVE_NAME       "Czerwona Studzienka"
SURVEY_ID       "CZSTD1"
SURVEY_NAME     "Czerwona Studzienka"
UPDATE_DATE     "2026-06-05"
PROJECT_NAME    "Kataster jaskin tatrzanskich"
COORDINATOR     "nieznane"
COORDINATOR_EMAIL "nieznane"
SOURCE_REF      "_RAW/01"
LICENSE         "http://creativecommons.org/licenses/by-sa/4.0/"

TEAM            "nieznane"
INSTRUMENT      "nieznane"
SURVEY_DATE     "2002-09-08"
SURVEY_GRADE    "nieznane"
PROCESSING      "dodano metadane do istniejacego aktywnego pliku SRV"
#]

#units meters order=DAV
#units A=D V=D
#prefix CzerwonaStudzienka
;Z. Tabaczynski
#DATE 2002-09-08
; Otwor w tym pliku: CzerwonaStudzienka:0 - fix/flag/note w Poligony/OTWORY.SRV
0	1	12	0	-90
