#[
CAVE_ID			"T.E-09.45"
CAVE_NAME		"Lustrzany Korytarz"
UPDATE_DATE		2026-03-07
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
REFERENCE_SYSTEM	"WGS84"
COORDINATE_SYSTEM	"UTM"
DATA_SOURCE		"Panstwowy Instytut Geologiczny, J. Nowak"
LICENSE			"http://creativecommons.org/licenses/by-sa/2.0/"
#]

#prefix lustkor
#flag	0	/Lustrzany Korytarz
#note	0	/Lustrzany Korytarz
#fix	0	E19.878350	N49.237530	1530.0m	;wsp. wg PIG (T.E-09.45)
