#[
CAVE_ID			T.E-08.07
CAVE_NAME		"Smocza Jama"
UPDATE_DATE		2015-07-26
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
REFERENCE_SYSTEM	"WGS84"
COORDINATE_SYSTEM	"UTM"
DATA_SOURCE		"Polskie Towarzystwo Przyjaciol Nauk o Ziemi"
LICENSE			"http://creativecommons.org/licenses/by-sa/2.0/"

TEAM "unknown"
INSTRUMENT "unknown"
#]

#prefix SM_A1_COORD
#FIX  o1  E19:52:03.841 N49:14:16.225   1120m
