#[
CAVE_ID			"unknown"
CAVE_NAME		"Jaskinia Mylna"
UPDATE_DATE		2026-02-12
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
REFERENCE_SYSTEM	"WGS84"
COORDINATE_SYSTEM	"UTM"
DATA_SOURCE		"Polskie Towarzystwo Przyjaciol Nauk o Ziemi"
LICENSE			"http://creativecommons.org/licenses/by-sa/2.0/"

TEAM  "unknown"
INSTRUMENT "unknown"
#]

#Units meters order=dav
#prefix ML
#flag	0	/Mylna
#note	0	/Mylna
#fix	0	417179.14	5454690.67	1098
