#[
CAVE_ID			"T.E-08.04"
CAVE_NAME		"Jaskinia Mylna"
SURVEY_ID		ULPAWLCG
SURVEY_NAME		"Ulica Pawlikowskiego-CG"
UPDATE_DATE		2026-02-12
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
DATA_SOURCE		"F. Filar"
LICENSE			"http://creativecommons.org/licenses/by-sa/2.0/"

TEAM "F. Filar" TODO: reszta zespolu??
INSTRUMENT "DistoX2"
#]

#date 2009-01-01
#UNITS meters order=dav
#prefix ML
#Units A=D V=D

8	200	1.47	173	-6
200	201	5.08	215	-17
201	202	12.55	235	-1
202	203	13.48	243	-1
203	204	11.55	212	2
204	205	3.39	205	-10
205	206	8.18	224	11