#[
CAVE_ID			"T.E-08.04"
CAVE_NAME		"Jaskinia Mylna"
SURVEY_ID		WSZCZCG
SURVEY_NAME		"Wielka Szczelina-CG"
UPDATE_DATE		2026-02-12
PROJECT_NAME		"Kataster jaskin tatrzanskich"
COORDINATOR		"Dariusz Lubomski"
COORDINATOR_EMAIL	"darek.lubomski@gmail.com"
DATA_SOURCE		"F. Filar"
LICENSE			"http://creativecommons.org/licenses/by-sa/2.0/"

TEAM "F. Filar i M. Parczewski"
INSTRUMENT "DistoX2"
#]

#prefix ML
#date 2009-01-01
#UNITS meters order=dav
#Units A=D V=D

30	100	7.06	219	0
100	101	5.3	261	-4
101	102	11.41	224	-5
102	103	8.35	218	-29
103	104	7.33	329	-12
104	105	2.85	271	11